{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPenZ3qaOfXLJeodt2BikYV",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/krishnapriyasivakumar299-oss/beavers-choice-agents/blob/main/beaver_agent.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# beaver_agents.py\n",
        "# Multi-agent system for Beaver's Choice Paper Company\n",
        "# Implements Orchestrator + 4 worker agents using smolagents\n",
        "# All 7 helper functions from project_starter.py are wrapped as tools\n",
        "\n",
        "from smolagents import tool, Agent\n",
        "from project_starter import (\n",
        "    create_transaction,\n",
        "    get_all_inventory,\n",
        "    get_stock_level,\n",
        "    get_supplier_delivery_date,\n",
        "    get_cash_balance,\n",
        "    generate_financial_report,\n",
        "    search_quote_history\n",
        ")\n",
        "\n",
        "# ------------------ TOOLS ------------------\n",
        "\n",
        "@tool\n",
        "def tool_create_transaction(order: dict):\n",
        "    \"\"\"Finalize a sales transaction and update the database.\"\"\"\n",
        "    return create_transaction(order)\n",
        "\n",
        "@tool\n",
        "def tool_get_all_inventory():\n",
        "    \"\"\"Return the full inventory list.\"\"\"\n",
        "    return get_all_inventory()\n",
        "\n",
        "@tool\n",
        "def tool_get_stock_level(item_id: int):\n",
        "    \"\"\"Check stock level for a specific item.\"\"\"\n",
        "    return get_stock_level(item_id)\n",
        "\n",
        "@tool\n",
        "def tool_get_supplier_delivery_date(item_id: int):\n",
        "    \"\"\"Estimate supplier delivery timeline for an item.\"\"\"\n",
        "    return get_supplier_delivery_date(item_id)\n",
        "\n",
        "@tool\n",
        "def tool_get_cash_balance():\n",
        "    \"\"\"Retrieve the current cash balance.\"\"\"\n",
        "    return get_cash_balance()\n",
        "\n",
        "@tool\n",
        "def tool_generate_financial_report():\n",
        "    \"\"\"Generate a financial summary report.\"\"\"\n",
        "    return generate_financial_report()\n",
        "\n",
        "@tool\n",
        "def tool_search_quote_history(customer_id: int):\n",
        "    \"\"\"Retrieve past quotes for a customer.\"\"\"\n",
        "    return search_quote_history(customer_id)\n",
        "\n",
        "# ------------------ AGENTS ------------------\n",
        "\n",
        "class InventoryAgent(Agent):\n",
        "    def run(self, item_id: int):\n",
        "        stock = tool_get_stock_level(item_id)\n",
        "        if stock < 10:\n",
        "            return {\n",
        "                \"status\": \"low\",\n",
        "                \"delivery\": tool_get_supplier_delivery_date(item_id)\n",
        "            }\n",
        "        return {\"status\": \"ok\", \"stock\": stock}\n",
        "\n",
        "class QuoteAgent(Agent):\n",
        "    def run(self, customer_id: int, item_id: int, quantity: int):\n",
        "        history = tool_search_quote_history(customer_id)\n",
        "        base_price = 10  # placeholder pricing logic\n",
        "        if quantity >= 100:\n",
        "            price = base_price * quantity * 0.9\n",
        "            reason = \"Bulk discount applied\"\n",
        "        else:\n",
        "            price = base_price * quantity\n",
        "            reason = \"Standard pricing\"\n",
        "        return {\"quote\": price, \"reason\": reason, \"history\": history}\n",
        "\n",
        "class SalesAgent(Agent):\n",
        "    def run(self, order: dict):\n",
        "        return tool_create_transaction(order)\n",
        "\n",
        "class FinanceAgent(Agent):\n",
        "    def run(self):\n",
        "        balance = tool_get_cash_balance()\n",
        "        report = tool_generate_financial_report()\n",
        "        return {\"balance\": balance, \"report\": report}\n",
        "\n",
        "# ------------------ ORCHESTRATOR ------------------\n",
        "\n",
        "class OrchestratorAgent:\n",
        "    def handle_request(self, request: dict):\n",
        "        req_type = request.get(\"type\")\n",
        "        if req_type == \"inventory\":\n",
        "            return InventoryAgent().run(request[\"item_id\"])\n",
        "        elif req_type == \"quote\":\n",
        "            return QuoteAgent().run(\n",
        "                request[\"customer_id\"],\n",
        "                request[\"item_id\"],\n",
        "                request[\"quantity\"]\n",
        "            )\n",
        "        elif req_type == \"sale\":\n",
        "            return SalesAgent().run(request[\"order\"])\n",
        "        elif req_type == \"finance\":\n",
        "            return FinanceAgent().run()\n",
        "        else:\n",
        "            return {\"error\": \"Unknown request type\"}"
      ],
      "metadata": {
        "id": "XNe0JQrACWLM"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}